Repository boostcampwm-2021/web28-NaBaaang, pull requests merged in 2021-12, with the labels that each got.

#260 fetch 로직 추상화 & fetchAction에서 api 호출까지 하도록 변경
  backend/package.json
  backend/src/lib/error/ErrorSpec.js
  backend/src/lib/util/jwtUtil.js
  backend/src/models/index.js
  backend/src/routes/api/auth/auth.service.js
  backend/src/routes/api/channel/channel.controller.js
  backend/src/routes/api/user/user.service.js
  frontend/src/apis/auth.js
  frontend/src/apis/channel.js
  frontend/src/apis/fetchAction.js
  frontend/src/apis/fetchUtill.js
  frontend/src/apis/user.js
  frontend/src/components/DashBoard/DashBoard.jsx
  frontend/src/components/DashBoard/DashBoardInfo/DashBoardInfo.jsx
  frontend/src/components/HLS/HLSVideo/HLSVideo.jsx
  frontend/src/components/HLS/hooks/useHLSPolling.js
  frontend/src/components/Header/hooks/useSignOutMenu.js
  frontend/src/components/OauthCallback/GoogleAuthCallback.jsx
  frontend/src/components/SideBar/SideBarStreamerList/SideBarStreamerList.jsx
  frontend/src/constants/fetchAction.js
  frontend/src/constants/fetchOptionTemplate.js
  frontend/src/constants/url.js
  frontend/src/hooks/useAuth.js
  frontend/src/hooks/useFetch.js
  frontend/src/socket/channel.js
  frontend/src/util/fetchUtil.js
  frontend/src/util/index.js
  socket/controllers/channel.js
  socket/loader.js
  socket/package.json
  socket/utils/user.js
Labels: 💻 frontend, :broom: refactoring

#262 cross-env 설치를 통해 환경 변수 통일
  backend/package.json
  backend/yarn.lock
  socket/package.json
  socket/yarn.lock
Labels: 🔨 fix

#265 git ignorecase false 설정
  frontend/src/store/UserStore.js
Labels: 🔥 hotfix

#267 Backend babel 설정 devDependency에서 dependency로 이동
  backend/package.json
Labels: 🔥 hotfix

#269 배포 화면의 버그 수정
  frontend/src/assets/images/channel-thumbnail.jpg
  frontend/src/components/Channel/ChannelDetail/ChannelDetail.jsx
  frontend/src/components/Common/Button/Button.jsx
  frontend/src/components/Common/Chip/Chip.jsx
  frontend/src/components/Header/Header.jsx
  frontend/src/components/LiveCollection/LiveList/LiveSlider/LiveCard/LiveCard.jsx
  frontend/src/components/LiveCollection/LiveList/LiveSlider/LiveCard/LiveDetail/LiveDetail.jsx
  frontend/src/components/ModalContent/Channel/ChannelForm/ChannelForm.jsx
  frontend/src/pages/Main/Main.jsx
  frontend/src/validation/ChannelModal.js
Labels: 🔥 hotfix

#271 BUTTON_COLOR_TYPE 수정 및 Button의 Typhography 색상 제거
  frontend/src/components/Common/Button/Button.jsx
  frontend/src/components/Common/Typography/Typography.jsx
  frontend/src/constants/css.js
Labels: 💻 frontend, 🔥 hotfix, :broom: refactoring
